on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

name: Milwaukee weather update

jobs:
  render:
    name: Update graphs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # use Posit's CRAN mirror with precompiled binaries
          use-public-rspm: true
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2 # automatically sets up cache
        with:
          packages: |
            any::ggplot2 
            any::readr
            any::tidyr
            any::dplyr
            any::lubridate
            any::stringr
            any::ggrepel
            any::scales
            any::here
      
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Retrieve data
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: Rscript -e 'source("R/Retrieve_GHCN_USW00014839.R")'
          continue_on_error: true
          
      - name: Build temperature graph
        run:  Rscript -e 'source("R/BuildDailyHigh.R")'
        
      - name: Build precipitation graph
        run:  Rscript -e 'source("R/BuildCumulativePrecipitation.R")'
        
      - name: Commit graphs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update data & graphs
